## Required software

In [1]:
import ipyrad.analysis as ipa
import toytree
import ipcoal
print('ipyrad', ipa.__version__)
print('toytree', toytree.__version__)
print('ipcoal', ipcoal.__version__)

ipyrad 0.9.63
toytree 2.0.5
ipcoal 0.1.5

# Taiwan + Southern China

### Input data file

In [2]:
# the path to your HDF5 formatted snps file
SNPS1 = "/rigel/dsi/users/slh2181/Pmontana/kudzu91_noHC_min20_100Loci_outfiles/kudzu91_noHC_min20_100Loci.snps.hdf5"
SNPS2 = "/rigel/dsi/users/slh2181/Pmontana/kudzu91_noHC_min6_outfiles/kudzu91_noHC_min6.snps.hdf5"

### Create IMAP for individuals

In [10]:
# imap for individual samples
IMAP1 = {
    "1": ["KTW1-11A"],
    "2": ["KTW1-14A"],
    "3": ["KTW1-15A"],
    "4": ["KTW1-1A"],
    "5": ["KTW1-22A"],
    "6": ["KTW1-23A"],
    "7": ["KTW1-3A"],
    "8": ["KTW1-4A"],
    "9": ["KTW1-7A"],
    "10": ["KTW1-9A"],
    "11": ["KTW4-12B"],
    "12": ["KTW4-13B"],
    "13": ["KTW4-15B"],
    "14": ["KTW4-17B"],
    "15": ["KTW4-18B"],
    "16": ["KTW4-19B"],
    "17": ["KTW4-20B"],
    "18": ["KTW4-21B"],
    "19": ["KTW4-22B"],
    "20": ["KTW4-24B"],
    "21": ["KTW6-12A"],
    "22": ["KTW6-15A"],
    "23": ["KTW6-17A"],
    "24": ["KTW6-18A"],
    "25": ["KTW6-1A"],
    "26": ["KTW6-23A"],
    "27": ["KTW6-24A"],
    "28": ["KTW6-2A"],
    "29": ["KTW6-5A"],
    "30": ["KTW6-7A"],
    "31": ["KFU7-10K"],
    "32": ["KFU7-11K"],
    "33": ["KFU7-12K"],
    "34": ["KFU7-16K"],
    "35": ["KFU7-21K"],
    "36": ["KFU7-25K"],
    "37": ["KFU7-5A"],
    "38": ["KFU7-7KA"],
    "39": ["KFU7-8KA"],
    "40": ["KFU7-2KA"],
    "41": ["KGD3-12A"],
    "42": ["KGD3-13A"],
    "43": ["KGD3-16A"],
    "44": ["KGD3-17A"],
    "45": ["KGD3-18A"],
    "46": ["KGD3-19A"],
    "47": ["KGD3-20A"],
    "48": ["KGD3-23A"],
    "49": ["KGD3-2A"],
    "50": ["KGD3-3A"],
   # "61": ["KGD3-5A"],
    "51": ["KGD4-10"],
    "52": ["KGD4-11A"],
   # "64": ["KGD4-13A"],
    #"65": ["KGD4-14A"],
    "53": ["KGD4-19"],
    "54": ["KGD4-1A"],
    #"68": ["KGD4-23"],
    "55": ["KGD4-24"],
    #"70": ["KGD4-2A"],
    #"71": ["KGD4-7A"],
    "56": ["KGD5-6A"],
    "57": ["KGD5-7A"],
    "58": ["KGU1-10A"],
    "59": ["KGU1-11A"],
    "60": ["KGU1-12A"],
    "61": ["KGU1-13A"],
    "62": ["KGU1-1A"],
    "63": ["KGU1-20A"],
    "64": ["KGU1-22A"],
    "65": ["KGU1-3A"],
    "66": ["KGU1-6A"],
    "67": ["KGU1-7A"],
    "68": ["KGU1-9A"],
#    "69": ["KHN5-10"],
#    "70": ["KHN5-11A"],
#    "71": ["KHN5-12A"],
#    "72": ["KHN5-13A"],
#    "73": ["KHN5-15A"],
#    "74": ["KHN5-16A"],
#    "75": ["KHN5-17A"],
#    "76": ["KHN5-1A"],
#    "77": ["KHN5-22A"],
#    "78": ["KHN5-24A"],
    "79": ["KHN7-10A"],
    "80": ["KHN7-11A"],
    "81": ["KHN7-16A"],
    "82": ["KHN7-17A"],
    "83": ["KHN7-19A"],
    "84": ["KHN7-22A"],
    "85": ["KHN7-2A"],
    "86": ["KHN7-5A"],
    "87": ["KHN7-6A"],
    "88": ["KHN7-7A"],
#    "89": ["KHN9-10A"],
#    "90": ["KHN9-12A"],
#    "91": ["KHN9-13A"],
#    "92": ["KHN9-14A"],
#    "93": ["KHN9-17A"],
#    "94": ["KHN9-20A"],
#    "95": ["KHN9-21A"],
#    "96": ["KHN9-22A"],
#    "97": ["KHN9-24A"],
#    "98": ["KHN9-7A"],
#    "99": ["KHN10-10A"],
#   "100": ["KHN10-13A"],
#   "101": ["KHN10-15A"],
#  "102": ["KHN10-17A"],
#   "103": ["KHN10-18A"],
#   "104": ["KHN10-1A"],
#   "105": ["KHN10-22A"],
#   "106": ["KHN10-23A"],
#   "107": ["KHN10-24A"],
#   "108": ["KHN10-7A"],
#"109": ["KHN11-15A"],
#"110": ["KHN11-1A"],
#"111": ["KHN11-8A"], #"KHN11-6A",
}

# apply filtering to the SNPs file
tool = ipa.snps_extracter(data=SNPS2, imap=IMAP1, mincov=.6, minmaf = 0.05, minmap={i:0 for i in IMAP1})
tool.parse_genos_from_hdf5();

Samples: 78
Sites before filtering: 298096
Filtered (indels): 5934
Filtered (bi-allel): 3288
Filtered (mincov): 261007
Filtered (minmap): 0
Filtered (subsample invariant): 205573
Filtered (minor allele frequency): 10483
Filtered (combined): 338892
Sites after filtering: 11236
Sites containing missing values: 10257 (91.29%)
Missing values in SNP matrix: 158729 (18.11%)
SNPs (total): 11236
SNPs (unlinked): 1972

In [3]:
IMAP2={
    "KTW1": ["KTW1-11A","KTW1-14A","KTW1-15A","KTW1-1A","KTW1-22A","KTW1-23A","KTW1-3A","KTW1-4A","KTW1-7A","KTW1-9A"],
"KTW4": ["KTW4-12B","KTW4-13B","KTW4-15B","KTW4-17B","KTW4-18B","KTW4-19B","KTW4-20B","KTW4-21B","KTW4-22B","KTW4-24B"],
"KTW6": ["KTW6-12A","KTW6-15A","KTW6-17A","KTW6-18A","KTW6-1A","KTW6-23A","KTW6-24A","KTW6-2A","KTW6-5A","KTW6-7A"],
    "KFU7": ["KFU7-10K","KFU7-11K","KFU7-12K","KFU7-16K","KFU7-21K","KFU7-25K","KFU7-5A","KFU7-7KA","KFU7-8KA","KFU7-2KA"],
"KGD3": ["KGD3-12A","KGD3-13A","KGD3-16A","KGD3-17A","KGD3-18A","KGD3-19A","KGD3-20A","KGD3-20A","KGD3-23A","KGD3-2A","KGD3-3A"],#"KGD3-5A"],
"KGD4": ["KGD4-10","KGD4-11A","KGD4-19","KGD4-1A","KGD4-24", #"KGD4-13A","KGD4-14A","KGD4-23","KGD4-2A","KGD4-7A"
#"KGD5": [
    "KGD5-6A","KGD5-7A"],
"KGU1": ["KGU1-10A","KGU1-11A","KGU1-12A","KGU1-13A","KGU1-1A","KGU1-20A","KGU1-22A","KGU1-3A","KGU1-6A","KGU1-7A","KGU1-9A"],
#"KHN5": ["KHN5-10","KHN5-11A","KHN5-12A","KHN5-13A","KHN5-15A","KHN5-16A","KHN5-17A","KHN5-1A","KHN5-1A","KHN5-22A","KHN5-24A"],
#"KHN9": ["KHN9-10A","KHN9-12A","KHN9-13A","KHN9-14A","KHN9-17A","KHN9-20A","KHN9-21A","KHN9-22A","KHN9-24A","KHN9-7A"],
"KHN7": ["KHN7-10A","KHN7-11A","KHN7-16A","KHN7-17A","KHN7-19A","KHN7-22A","KHN7-2A","KHN7-5A","KHN7-6A","KHN7-7A"],
#"KHN10": ["KHN10-10A","KHN10-13A","KHN10-15A","KHN10-17A","KHN10-18A","KHN10-1A","KHN10-22A","KHN10-23A","KHN10-24A","KHN10-7A"],
#"KHN11": ["KHN11-15A","KHN11-1A","KHN11-8A"], #"KHN11-6A",
}

In [9]:
# apply filtering to the SNPs file
tool = ipa.snps_extracter(data=SNPS2, imap=IMAP2, mincov=2, minmaf = 0.05, minmap={i:0.1 for i in IMAP2})
tool.parse_genos_from_hdf5();

Samples: 78
Sites before filtering: 298096
Filtered (indels): 5934
Filtered (bi-allel): 3288
Filtered (mincov): 111516
Filtered (minmap): 261641
Filtered (subsample invariant): 205573
Filtered (minor allele frequency): 10022
Filtered (combined): 339732
Sites after filtering: 10396
Sites containing missing values: 9417 (90.58%)
Missing values in SNP matrix: 186993 (23.06%)
SNPs (total): 10396
SNPs (unlinked): 1849

In [19]:
?ipa.snps_extracter

# get allele frequencies for unlinked SNPS only

In [11]:
#unlinked = ext.subsample_snps()
#ext.snps = unlinked
df = tool.get_population_geno_frequency()
from ipyrad.analysis.utils import jsubsample_snps
unlinked = jsubsample_snps(tool.snpsmap, seed=123)
unlinked2 = df.iloc[: , unlinked]
unlinked2

/rigel/home/slh2181/ipyrad/ipyrad/analysis/snps_extracter.py:385: RuntimeWarning: invalid value encountered in true_divide
  df.loc[:, pop] = deriv / (deriv + ances)

,0,3,10,13,20,21,23,31,38,45,...,11194,11197,11201,11207,11215,11221,11223,11225,11230,11235
1,NaN,0.0,0.0,0.0,0.0,NaN,0.5,1.0,0.5,0.0,...,0.5,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.5
10,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.5,0.5,...,0.5,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.5,1.0
11,NaN,0.0,0.0,0.0,0.0,NaN,0.0,1.0,0.5,0.0,...,1.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.5
12,NaN,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.5,0.0,...,1.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.5
13,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,...,1.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,0.0,0.5,0.0,0.0,0.0,0.5,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.5,0.0,NaN,0.5,0.0,1.0
86,0.0,0.5,0.0,0.0,0.0,0.5,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.5,0.0,NaN,0.5,0.0,1.0
87,0.0,0.5,0.0,0.0,0.0,NaN,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.5,0.0,NaN,0.5,0.0,1.0
88,0.0,0.5,0.0,0.0,0.0,0.5,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.5,0.0,NaN,0.5,0.0,1.0
9,0.0,0.0,0.0,0.0,0.0,NaN,0.5,1.0,0.5,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [12]:
# sort samples numerically
unlinked2.index = unlinked2.index.astype(int)
unlinked2 = unlinked2.sort_index()

# changa NaN to NA for proper conStruct format
strdf = unlinked2.astype(str)
strdf[strdf=="nan"] = "NA"
strdf

,0,3,10,13,20,21,23,31,38,45,...,11194,11197,11201,11207,11215,11221,11223,11225,11230,11235
1,NA,0.0,0.0,0.0,0.0,NA,0.5,1.0,0.5,0.0,...,0.5,0.0,0.0,NA,NA,0.0,0.0,0.0,0.0,0.5
2,NA,0.0,0.0,0.0,0.0,NA,0.0,1.0,0.0,NA,...,0.5,0.0,0.0,0.0,NA,0.0,0.5,0.0,0.5,0.5
3,NA,0.0,0.0,0.0,0.0,NA,0.5,0.0,0.5,0.0,...,0.0,0.0,0.0,0.5,NA,0.5,0.0,0.0,0.0,1.0
4,NA,0.0,0.0,0.0,0.0,NA,0.5,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.5
5,NA,0.0,0.0,0.0,0.0,NA,0.5,1.0,0.5,0.0,...,0.5,0.0,0.0,NA,NA,0.0,0.0,0.0,0.0,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,0.0,0.5,0.0,0.0,0.0,0.5,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,NA,0.5,0.0,NA,0.5,0.0,1.0
85,0.0,0.5,0.0,0.0,0.0,0.5,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.5,0.0,NA,0.5,0.0,1.0
86,0.0,0.5,0.0,0.0,0.0,0.5,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.5,0.0,NA,0.5,0.0,1.0
87,0.0,0.5,0.0,0.0,0.0,NA,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.5,0.0,NA,0.5,0.0,1.0
88,0.0,0.5,0.0,0.0,0.0,0.5,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.5,0.0,NA,0.5,0.0,1.0

### Write data to file

In [13]:
# write to a file
strdf.to_csv("./Taiwan/indiv_TW.fullChina_lessmiss_freqs3.csv")

In [1]:
! module load R/4.0.1

In [2]:
import rpy2
import rpy2.rinterface
print(rpy2.__version__)

3.4.1

In [3]:
from rpy2.robjects.packages import importr
# import R's "base" package
base = importr('base')

# import R's "utils" package
utils = importr('utils')

In [4]:
%load_ext rpy2.ipython

In [5]:
%%R
library("conStruct")

R[write to console]: Error in library("conStruct") : there is no package called 'conStruct'

R[write to console]: In addition:
R[write to console]: Warning messages:

R[write to console]: 1:
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]:

R[write to console]:  library '/usr/share/R/library' contains no packages

R[write to console]: 2:
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]:

R[write to console]:  library '/usr/share/R/library' contains no packages

R[write to console]: 3:
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]:

R[write to console]:  libraries '/rigel/home/slh2181/R/x86_64-redhat-linux-gnu-library/3.5', '/usr/share/R/library' contain no packages

Error in library("conStruct") : there is no package called 'conStruct'

In [9]:
# R package names
packnames = ('ggplot2', 'conStruct')

# R vector of strings
from rpy2.robjects.vectors import StrVector

# Selectively install what needs to be install.
# We are fancy, just because we can.
names_to_install = [x for x in packnames if not rpackages.isinstalled(x)]
if len(names_to_install) > 0:
    utils.install_packages(StrVector(names_to_install))

NameError: name 'rpackages' is not defined

### I need to run this in Rstudio, not in terminal.